name = "untitled"
author = "minecraft-modpack"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ba748787339aedb2dea41fda268afaaed8c6be3e31aaa64dd6c4ebae895cab1"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
datapack-folder = "datapacks"
