name = "untitled"
author = "minecraft-modpack"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5a7e335c98c3a3e7969616825bac76fdf4f6dca4df97a0ad6eee31b6d20dffc"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
datapack-folder = "datapacks"
