name = "untitled"
author = "minecraft-modpack"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1bf0f8eb3210767d887ce91bdd70150ad13af148cef8f855d2e6e91354d3e95"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
datapack-folder = "datapacks"
