name = "untitled"
author = "minecraft-modpack"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23ef4a66645a0221f042b71f6bd76bef859718049ad7ef934797cbc84097b1ef"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
datapack-folder = "datapacks"
