name = "untitled"
author = "minecraft-modpack"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "354f9d6bd2e08f5fdcb54954cdd5449aedd11e26563030609227e5e98f349ed1"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
datapack-folder = "datapacks"
